package src.main.model.knight;

public enum KnightState {
    IDLE, RUNNING, JUMPING, FALLING, DOUBLE_JUMPING, DASHING, ATTACKING, HURT;
    //AIRBORNE,
    //    DASH,
    //    DEATH,
    //    DOUBLE_JUMP,
    //    DOWN_SLASH,
    //    FALL,
    //    FIREBALL,
    //    FOCUS_END,
    //    FOCUS_GET,
    //    FOCUS_START,
    //    FOCUS,
    //    IDLE,
    //    IDLE_HURT,
    //    KNIGHT_FULL,
    //    LANDING,
    //    LOGO,
    //    LOOKDOWN,
    //    LOOKUP,
    //    RUN,
    //    RUN_TO_IDLE,
    //    SCREAM,
    //    SLASH,
    //    SLASH_ALT,
    //    UP_SLASH,
    //    WALK,
    //    WALK_SLIDE,
    //    WALL_JUMP,
}
