package src.main.model.entity.knight;

public enum KnightState {
    IDLE, RUNNING, JUMPING, FALLING, DOUBLE_JUMPING, DASHING,
    ATTACKING, ATTACKING_DOWN, ATTACKING_UP, FOCUSING, WALL_SLIDING,
    CASTING_VENGEFUL, CASTING_WRAITHS;
}
